include: package:flutter_lints/flutter.yaml

formatter:
  page_width: 120

linter:

  rules:
    avoid_print: false  
    prefer_single_quotes: true
    sized_box_for_whitespace: true
    non_constant_identifier_names: false


