name: code_forces_tracker
description: A new Flutter project.



publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  http: ^0.13.4
  font_awesome_flutter: ^9.1.0
  flutter_riverpod: ^0.14.0+3
  hooks_riverpod: ^0.14.0+5
  freezed: ^0.14.5
  flutter_lints: ^1.0.4
  build_runner: ^2.1.4
  json_serializable: ^5.0.2
  shared_preferences: ^2.0.8
  infinite_scroll_pagination: ^3.1.0
  url_launcher: ^6.0.12
  enum_to_string: ^2.0.1
  tuple: ^2.0.0
  charts_flutter:  
    git:
      url: https://github.com/google/charts
      path: charts_flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
